language: java
jdk:
  - oraclejdk7
addons:
  firefox: "34.0"
before_script:
  - cd ./cucumber-test/
script:
  - pwd
  - curl http://yaowenjie.github.io
  - gradle clean build
  - gradle test
  - cat ./build/reports/tests/index.html
