language: java
jdk:
  - oraclejdk7
addons:
  firefox: "34.0"
before_script:
  - cd ./cucumber-test/
script:
  - pwd
  - ls
  - curl http://www.baidu.com
  - curl http://yaowenjie.github.io
  - gradle test
